### ISSUE TITLE
README references file:///C:/Users/Jonas/repos..

### ISSUE THREAD

**Issue by johannjacobsohn** [jgliss/pyplis#12]
The changelog is linked to `<file:///C:/Users/Jonas/repos/pyplis/docs/_build/html/changelog.html#release-1-0-1-1-3-0>` which is probably a mistake.

**Comment by heliotropium72** [comment]
Is this still active? I couldn't find the link in the README.

**Comment by johannjacobsohn** [comment]
it is, in https://raw.githubusercontent.com/jgliss/pyplis/master/README.rst

```
In the following, a brief overview is provided over the most important changes associated with this release. Please see latest `changelog <file:///C:/Users/Jonas/repos/pyplis/docs/_build/html/changelog.html#release-1-0-1-1-3-0>`__ for a detailed description of all changes.
```

**Comment by heliotropium72** [comment]
Okay, now I see why I couldn't find it when it was never working. I fixed that one, but it is not relevant for the Readme of the py3 branch.
