### ISSUE TITLE
Update dependencies in readme

### ISSUE THREAD

**Issue by solvejgdinger** [jgliss/pyplis#14]
The dependencies are outdated due to the newer version of geonum. At least latlon has to be replaced by latlon23 but there might be more.

**Comment by johannjacobsohn** [comment]
This is fixed in the py3 branches requirements.txt. I think the readme should defer to that file for requirements, to avoid duplication and inconsistencies. The later file is also under unit test (using tox) and is less likely to be incorrect.

**Comment by jgliss** [comment]
Thanks for the hint. I will leave it in master as is for now, since py3 branch will be merged into master soon. Will also update the README then. Will leave this issue open until then.

**Comment by jgliss** [comment]
Is updated. I am closing this now.
