### ISSUE TITLE
Reference to non-existing folder in scripts/README.rst

### ISSUE THREAD

**Issue by johannjacobsohn** [jgliss/pyplis#21]
`Folder containing pyplis example scripts. Most of these scripts use the pyplis test dataset from Mt. Etna, which can be installed as described below. Old versions of the example scripts for previous pyplis versions can be found in the folder old_versions.`

https://github.com/jgliss/pyplis/blob/master/scripts/README.rst

There is no folder `old_versions`.

**Comment by jgliss** [comment]
Thanks for the hint! I updated accordingly!
