### ISSUE TITLE
Move tests from example scripts into test suite

### ISSUE THREAD

**Issue by jgliss** [jgliss/pyplis#25]
Currently the example scripts contain high-level tests at the end that ensure that the basic analysis works. These tests should be migrated into the test-suite as testing should ideally not be done within the example scripts (it was a convenient quick solution due to lack of time).

The corresponding tests should / could use [pytest.skipif markers](https://docs.pytest.org/en/latest/skipping.html#id1) (or similar) to make sure they are only run if the pyplis example data is available.

**Comment by johannjacobsohn** [comment]
I dont think this is necessary if we plan to move to notebooks anyway. With Tox/travis, the scripts are used as high-level integration tests and probably should stay that way.

**Comment by jgliss** [comment]
Thanks, Johann. I agree that this is not an urgent matter for now and that it can stay the way it is.
