### ISSUE TITLE
through_origin parameter is not working correctly in DoasCalibData.fit_calib_polynomial()

### ISSUE THREAD

**Issue by heliotropium72** [jgliss/pyplis#3]
The parameter through_origin does not force the fit through the origin when few data is available.
In the below figure I used `DoasCalibData.fit_calib_polynomial` with `through_origin=True` (blue curve) and a simple least square fit (red curve, code below). The blue curve does not go through zero whereby it is different than the non-forced curve (see below).
I suggest that you replace the additional zero-data with a simpler fit model or a different function.

With `through_origin=True` 
![figure_5_lstsq](https://user-images.githubusercontent.com/23701773/34115231-4e64d0e4-e415-11e7-9779-944207ef27bb.png)

With `through_origin=False` 
![figure_5](https://user-images.githubusercontent.com/23701773/34115387-c670658a-e415-11e7-8cf9-dca5c359bb1c.png)

```
def fit_linear(calib, plot=False):
    """ Simple linear fit with forced origin """
    tau = calib.tau_vec
    scd = calib.doas_vec
    tau = tau[:,np.newaxis]
    a, res, rank, sgl = np.linalg.lstsq(tau, scd)
    if plot:
        fig, ax = plt.subplots()
        plt.plot(tau, scd, 'bo')
        plt.plot(tau, a*tau, 'r-', label='forced origin')
        ax.set_xlabel(r'$\tau$')
        ax.set_ylabel(r'SO$_2$ SCD [molec/cm$^{2}$]')
        ax.grid()
        plt.show()
    return a
```

**Comment by jgliss** [comment]
Thanks for this hint. This has been resolved in the latest commit. 

**NOTE**
This fix will be included in the next upcoming release and is not included in the current release 1.0.1. In case you need this functionality, please clone the current version of the repo.

Cheers
