### ISSUE TITLE
Installation of OpenCV dependencies

### ISSUE THREAD

**Issue by heliotropium72** [jgliss/pyplis#4]
This is only a comment on the installation of pyplis.

The packages listed under Requirements can all be easily installed using anaconda and `conda install <package>` (or pip for geonum and pydoas). However when installing opencv, it will also upgrade the python distribution from 2.x to 3.x and thus break the pyplis installation. While it does state the planed upgrade, it does not warn explicitly about it while installing opencv. So I want to raise awareness for this potential problem. Instead OpenCV could be installed from the [Anaconda Cloud](https://anaconda.org/search?q=opencv) selecting the desired version e.g. with `conda install -c conda-forge opencv` for v3.3.0.

Since I had to recreate the anaconda environment anyway, so I have attached the anaconda enviornment file after the succesful installation of all dependencies (pyplis 1.0.0): [environment.txt](https://github.com/jgliss/pyplis/files/1600757/environment.txt). 
I hope it might help someone in the future. (The file ending was changed from *.yml to *.txt in order to upload it. Change it back in case you want to use it.)

**Comment by jgliss** [comment]
@oryalava I'm very sorry but I realised that I had deactivated notfications here and I missed your comment. pyplis was never tested on macOS so I can imagine that it does not work out of the box. Did you manage to install it?

@heliotropium72 This does not seem to be a problem anymore (I just updated my py27 opencv v2.4.11 to v3.2.0 using `conda install -c conda-forge opencv` without problems. 

So I close this issue.
